import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import JSZip from 'jszip';
import { afterEach, describe, expect, it } from 'vitest';
import { buildRendererInput, hashJson, resolveRenderer } from './courseware-renderer-contract.js';
import { promoteCanonical, renderCourseware } from './courseware-renderer-registry.js';

const dirs=[]; afterEach(()=>dirs.splice(0).forEach((dir)=>fs.rmSync(dir,{recursive:true,force:true})));
function fixture(options={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'renderer-registry-'));dirs.push(dir);const slides=options.slides||[{id:'slide-01',type:'cover',title:'条件判断',html:'<section><h1>条件判断</h1><p>把题意翻译成真假问题</p></section>',notes:'先让学生预测。',questionRefs:[{question_id:'q-1',oj_problem_id:'p-1'}]},{id:'slide-02',type:'code',title:'边界测试',html:'<section><h2>边界测试</h2><pre>if (x &gt;= 38) {\n  rest();\n}</pre><p>检查边界前、边界点、边界后。</p></section>',notes:'强调等号。'}];fs.writeFileSync(path.join(dir,'courseware-slides.json'),JSON.stringify({schemaVersion:'tiku.coursewareSlides.v1',coursePackageId:'demo',lessonDbId:'db-6',lessonId:'lesson-06',studentVisibility:'student',slides}));fs.writeFileSync(path.join(dir,'approved-style.json'),JSON.stringify({teacherApprovedStyleId:'style-b',designTokens:{colors:{accent:'#F97316'}}}));return dir;}

describe('courseware renderer registry',()=>{
 it('parses explicit renderers and blocks unknown values',()=>{expect(resolveRenderer('pilot-html')).toBe('pilot-html');expect(()=>resolveRenderer('secret-fallback')).toThrow(/Unknown/);});
 it('creates reproducible source/style hashes without changing identity fields',()=>{const dir=fixture();const a=buildRendererInput({projectPath:dir,runId:'r1'});const b=buildRendererInput({projectPath:dir,runId:'r2'});expect(a.sourceHash).toBe(b.sourceHash);expect(a.styleHash).toBe(b.styleHash);expect(a.questionRefs[0]).toMatchObject({question_id:'q-1',oj_problem_id:'p-1'});});
 it('blocks student-visible production wording',async()=>{const dir=fixture({slides:[{id:'s1',html:'<section>PilotDeck agent 内部教研</section>'}]});await expect(renderCourseware({projectPath:dir,runId:'r',renderer:'pilot-html',operationMode:'audit-only'})).rejects.toThrow(/student-visible/);});
 it('audit-only does not create renderer outputs',async()=>{const dir=fixture();const result=await renderCourseware({projectPath:dir,runId:'r',renderer:'codex-artifact',operationMode:'audit-only'});expect(result.status).toBe('ready-for-teacher-review');expect(fs.existsSync(path.join(dir,'outputs','codex-artifact'))).toBe(false);});
 it('requires explicit authorization and snapshots full-rebuild inputs',async()=>{const dir=fixture();await expect(renderCourseware({projectPath:dir,runId:'r',renderer:'pilot-html',operationMode:'full-rebuild'})).rejects.toThrow(/authorization/);await renderCourseware({projectPath:dir,runId:'r2',renderer:'pilot-html',operationMode:'full-rebuild',fullRebuildAuthorized:true,options:{chromeExecutable:'/bin/false'}}).catch(()=>{});expect(fs.existsSync(path.join(dir,'.renderer-snapshots','r2','courseware-slides.json'))).toBe(true);});
 it('does not promote before teacher approval or when validation is blocked',()=>{const dir=fixture();const report={status:'ready-for-teacher-review',validation:{status:'pass'},sourceHash:'s',styleHash:'t'};expect(()=>promoteCanonical(dir,'r','pilot-html',report)).toThrow(/Teacher approval/);expect(()=>promoteCanonical(dir,'r','pilot-html',{...report,status:'blocked'},{approvedBy:'teacher'})).toThrow(/cannot be promoted/);const canonical=promoteCanonical(dir,'r','pilot-html',report,{approvedBy:'teacher-a'});expect(canonical.publishAllowed).toBe(false);});
 it('generates an editable PPTX with notes and matching page count via our PPTXGenJS adapter',async()=>{const dir=fixture();const report=await renderCourseware({projectPath:dir,runId:'native-real',renderer:'anthropic-pptxgenjs'});expect(report.status).toBe('ready-for-teacher-review');expect(report.editable).toBe(true);expect(report.validation).toMatchObject({status:'pass',slideCount:2,notesCount:2});const pptx=path.join(dir,'outputs','anthropic-pptxgenjs','courseware.pptx');const zip=await JSZip.loadAsync(fs.readFileSync(pptx));expect(zip.file('ppt/slides/slide2.xml')).not.toBeNull();expect(zip.file('ppt/notesSlides/notesSlide2.xml')).not.toBeNull();});
 it('keeps prior renderer output when a later run fails',async()=>{const dir=fixture();await renderCourseware({projectPath:dir,runId:'good',renderer:'anthropic-pptxgenjs'});const before=hashJson(fs.statSync(path.join(dir,'outputs','anthropic-pptxgenjs','courseware.pptx')).size);fs.writeFileSync(path.join(dir,'courseware-slides.json'),JSON.stringify({studentVisibility:'student',slides:[{id:'bad',html:'<section>内部教研</section>'}]}));await expect(renderCourseware({projectPath:dir,runId:'bad',renderer:'anthropic-pptxgenjs'})).rejects.toThrow();expect(fs.existsSync(path.join(dir,'outputs','anthropic-pptxgenjs','courseware.pptx'))).toBe(true);expect(hashJson(fs.statSync(path.join(dir,'outputs','anthropic-pptxgenjs','courseware.pptx')).size)).toBe(before);});
});
